/* ═══════════ THEME LAYER ═══════════
   Style objects (S). Design system consumers. */

import { T, D } from "./constants";

export const S = {
  root: { position: "fixed", inset: 0, background: `radial-gradient(120% 80% at 50% 30%, #121A31 0%, ${T.bg} 70%)`, color: T.ink, fontFamily: "'Nunito', system-ui, sans-serif", display: "flex", flexDirection: "column", overflow: "hidden", userSelect: "none", WebkitTapHighlightColor: "transparent" },
  hud: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "16px 20px 10px" },
  roundLabel: { fontWeight: 900, fontSize: 18, color: T.ink },
  colorCount: { fontWeight: 700, fontSize: 12, color: T.muted, marginTop: 2 },
  movesLabel: { fontWeight: 900, fontSize: 22, fontVariantNumeric: "tabular-nums" },
  movesSub: { fontWeight: 700, fontSize: 11, color: T.muted, marginLeft: 4 },
  progressTrack: { height: 4, margin: "0 20px 8px", background: T.line, borderRadius: 999, overflow: "hidden" },
  progressFill: { height: "100%", borderRadius: 999, transition: "all 300ms ease" },
  upgradeStrip: { display: "flex", gap: 4, padding: "0 20px 8px", flexWrap: "wrap" },
  board: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", padding: 20 },
  tubesRow: { display: "flex", flexWrap: "wrap", gap: 12, justifyContent: "center", alignItems: "flex-end", maxWidth: 400 },
  footer: { padding: "12px 20px 32px", minHeight: 60, display: "flex", justifyContent: "center", alignItems: "center" },
  hint: { fontSize: 13, fontWeight: 700, color: T.muted, textAlign: "center" },
  ovTop: { position: "fixed", inset: 0, background: "rgba(10,15,31,0.94)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20, backdropFilter: "blur(8px)", zIndex: 90 },
  overlay: { position: "fixed", inset: 0, background: "rgba(10,15,31,0.94)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20, backdropFilter: "blur(8px)" },
  ovCard: { background: T.card, border: `1px solid ${T.edge}`, borderRadius: 24, padding: 24, textAlign: "center", maxWidth: 320, width: "100%", boxShadow: "0 24px 60px rgba(0,0,0,0.5)" },
  ovIconCircle: { width: 64, height: 64, borderRadius: 20, background: `${T.danger}22`, border: `2px solid ${T.danger}55`, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 16px" },
  ovBigNum: { fontSize: 72, fontWeight: 900, color: T.ink, letterSpacing: "-0.05em", lineHeight: 1, marginTop: 8 },
  ovBigLabel: { fontSize: 11, fontWeight: 900, letterSpacing: "0.15em", color: T.muted, marginTop: 6, textTransform: "uppercase" },
  ovNewBest: { display: "inline-block", background: `${T.gold}22`, border: `1px solid ${T.gold}66`, color: T.gold, fontSize: 12, fontWeight: 900, padding: "6px 14px", borderRadius: 999, marginTop: 12 },
  ovStats: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 8, margin: "20px 0 20px" },
  ovStat: { background: `${T.bg}80`, border: `1px solid ${T.edge}`, borderRadius: 14, padding: "12px 6px", textAlign: "center" },
  ovStatNum: { fontSize: 22, fontWeight: 900, color: T.ink, letterSpacing: "-0.02em", fontVariantNumeric: "tabular-nums" },
  ovStatLabel: { fontSize: 9, fontWeight: 800, color: T.muted, letterSpacing: "0.08em", textTransform: "uppercase", marginTop: 4 },
  dailyBadge: { display: "inline-block", fontSize: 9, fontWeight: 900, letterSpacing: "0.1em", color: T.gold, background: `${T.gold}22`, border: `1px solid ${T.gold}66`, padding: "2px 6px", borderRadius: 6, marginRight: 6, verticalAlign: "middle" },
  comboBadge: { display: "flex", alignItems: "center", gap: 6, alignSelf: "center", background: `${T.gold}22`, border: `1px solid ${T.gold}66`, borderRadius: 999, padding: "5px 12px 5px 10px", marginBottom: 6 },
  comboFlame: { fontSize: 13 },
  comboText: { fontSize: 12, fontWeight: 900, color: T.gold, letterSpacing: "0.02em", fontVariantNumeric: "tabular-nums" },
  /* ─── HOME SCREEN ─── */
  homeRoot: { position: "fixed", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", background: "#05070F", overflow: "hidden" },
  homeAmbient: { position: "absolute", inset: 0, background: "radial-gradient(80% 60% at 20% 15%, rgba(76, 141, 255, 0.10) 0%, transparent 55%), radial-gradient(70% 50% at 85% 75%, rgba(255, 194, 75, 0.06) 0%, transparent 55%), linear-gradient(180deg, #05070F 0%, #0A0F1F 100%)", pointerEvents: "none" },
  homeContent: { position: "relative", display: "flex", flexDirection: "column", alignItems: "center", gap: D.s24, padding: D.s24, width: "100%", maxWidth: 380 },
  homeTitleBlock: { textAlign: "center", marginBottom: D.s8 },
  homeTitle: { fontSize: 52, lineHeight: 1, color: D.text },
  homeSubtitle: { color: D.textSub, marginTop: D.s12 },
  homePlayBtn: { position: "relative", display: "flex", alignItems: "center", justifyContent: "center", width: "100%", height: 68, border: "none", borderRadius: D.rPill, background: D.accentGrad, color: "#fff", cursor: "pointer", fontFamily: "'Plus Jakarta Sans', sans-serif", boxShadow: `${D.accentGlow}, inset 0 1px 0 rgba(255,255,255,0.2)`, overflow: "hidden" },
  homePlayGlow: { position: "absolute", inset: 0, background: "radial-gradient(60% 100% at 50% 0%, rgba(255,255,255,0.25) 0%, transparent 60%)", pointerEvents: "none" },
  homePlayInner: { position: "relative", display: "flex", alignItems: "center", gap: D.s12 },
  homePlayIcon: { fontSize: 22, lineHeight: 1 },
  homePlayText: { fontSize: 24, lineHeight: 1 },
  homeDailyCard: { display: "flex", flexDirection: "column", gap: D.s16, width: "100%", background: D.glassStandard, backdropFilter: "blur(20px) saturate(140%)", WebkitBackdropFilter: "blur(20px) saturate(140%)", border: "1px solid rgba(255, 194, 75, 0.32)", borderRadius: D.rCard, padding: D.s16 + " " + D.s24, cursor: "pointer", fontFamily: "'Inter', sans-serif", textAlign: "left", color: D.text, boxShadow: D.shadowMd },
  homeDailyHeader: { display: "flex", alignItems: "center", gap: D.s8 },
  homeDailyIcon: { fontSize: 18, lineHeight: 1 },
  homeDailyLabel: { flex: 1, color: D.gold },
  homeStreak: { display: "flex", alignItems: "center", gap: D.s4, background: "rgba(255, 194, 75, 0.18)", border: "1px solid rgba(255, 194, 75, 0.4)", padding: "4px 10px", borderRadius: D.rPill },
  homeStreakNum: { fontSize: 13, color: D.gold },
  homeWeekRow: { display: "flex", justifyContent: "space-between", gap: D.s4, paddingTop: D.s4 },
  homeDayCol: { display: "flex", flexDirection: "column", alignItems: "center", gap: D.s8, flex: 1 },
  homeDayLabel: { fontSize: 10, fontWeight: 800, color: D.textSub, letterSpacing: "0.08em", fontFamily: "'Inter', sans-serif" },
  homeDayDot: { width: 22, height: 22, borderRadius: "50%", border: "1.5px solid transparent", transition: `all ${D.tQuick}` },
  homeDailyCta: { fontSize: 12, fontWeight: 700, textAlign: "center", letterSpacing: "0.01em", fontFamily: "'Inter', sans-serif" },
  homeFooterRow: { display: "flex", alignItems: "center", gap: D.s12, marginTop: D.s8 },
  homeIconBtn: { width: 48, height: 48, borderRadius: D.rSm, border: `1px solid ${D.glassBorder}`, color: D.textSub, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, fontFamily: "'Inter', sans-serif" },
  homeAchPill: { display: "flex", alignItems: "center", gap: D.s8, border: `1px solid ${D.glassBorder}`, borderRadius: D.rPill, padding: "12px 18px", fontFamily: "'Inter', sans-serif" },
  settingRow: { display: "flex", alignItems: "center", justifyContent: "space-between", width: "100%", background: `${T.bg}80`, border: `1px solid ${T.edge}`, borderRadius: 14, padding: "14px 16px", cursor: "pointer", fontFamily: "'Nunito', sans-serif", color: T.ink },
  settingLabel: { fontWeight: 800, fontSize: 14 },
  togglePill: { fontSize: 10, fontWeight: 900, letterSpacing: "0.1em", color: "#fff", padding: "4px 10px", borderRadius: 999 },
  tutOverlay: { position: "fixed", inset: 0, background: "rgba(10,15,31,0.95)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20, backdropFilter: "blur(10px)", zIndex: 100 },
  tutCard: { background: T.card, border: `1px solid ${T.edge}`, borderRadius: 28, padding: 28, maxWidth: 380, width: "100%", boxShadow: "0 32px 80px rgba(0,0,0,0.6)" },
  tutHeader: { textAlign: "center", marginBottom: 24 },
  tutIconCircle: { width: 64, height: 64, borderRadius: 20, background: `${T.accent}22`, border: `2px solid ${T.accent}55`, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 12px" },
  tutTitle: { fontWeight: 900, fontSize: 24, color: T.ink, letterSpacing: "-0.02em" },
  tutSub: { fontSize: 13, fontWeight: 700, color: T.muted, marginTop: 4 },
  tutSteps: { display: "flex", flexDirection: "column", gap: 14, marginBottom: 20 },
  tutStep: { display: "flex", alignItems: "flex-start", gap: 14 },
  tutNum: { width: 32, height: 32, borderRadius: 10, background: T.accent, color: "#fff", fontWeight: 900, fontSize: 15, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  tutStepBody: { flex: 1, minWidth: 0, paddingTop: 2 },
  tutStepTitle: { fontWeight: 900, fontSize: 15, color: T.ink },
  tutStepDesc: { fontSize: 13, fontWeight: 600, color: T.muted, marginTop: 2, lineHeight: 1.45 },
  tutWarning: { display: "flex", alignItems: "center", gap: 10, background: `${T.danger}15`, border: `1px solid ${T.danger}44`, borderRadius: 14, padding: "10px 14px", marginBottom: 20, fontSize: 12, fontWeight: 700, color: T.ink, lineHeight: 1.4 },
  ovTitle: { fontWeight: 900, fontSize: 28, letterSpacing: "-0.02em" },
  ovSub: { fontSize: 14, fontWeight: 600, color: T.muted, marginTop: 8, marginBottom: 24 },
  primary: { display: "block", width: "100%", background: T.accent, color: "#fff", border: "none", borderRadius: 999, padding: "14px 24px", fontFamily: "'Nunito', sans-serif", fontWeight: 900, fontSize: 15, cursor: "pointer", boxShadow: `0 8px 24px ${T.accent}55` },
  ghost: { display: "block", width: "100%", background: "transparent", color: T.muted, border: "none", padding: 12, fontFamily: "'Nunito', sans-serif", fontWeight: 800, fontSize: 13, cursor: "pointer", marginTop: 6 },
};
