/* ═══════════ THEME LAYER ═══════════
   Style objects (S). Design system consumers. */

import { T, D } from "./constants";

export const S = {
  root: { position: "fixed", inset: 0, background: `radial-gradient(120% 80% at 50% 30%, #121A31 0%, ${T.bg} 70%)`, color: T.ink, fontFamily: "'Nunito', system-ui, sans-serif", display: "flex", flexDirection: "column", overflow: "hidden", userSelect: "none", WebkitTapHighlightColor: "transparent" },
  hud: {
    display: "flex", alignItems: "center", justifyContent: "space-between",
    padding: "calc(env(safe-area-inset-top, 0px) + 14px) 20px 10px",
  },
  roundLabel: {
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    fontWeight: 900, fontSize: 20, color: "var(--text)",
    letterSpacing: "-0.02em", lineHeight: 1.1,
  },
  colorCount: {
    fontFamily: "'Inter', system-ui, sans-serif",
    fontWeight: 600, fontSize: 11.5, color: "var(--text-sub)", marginTop: 3,
    letterSpacing: "0.01em",
  },
  movesLabel: {
    fontFamily: "'JetBrains Mono', monospace",
    fontWeight: 800, fontSize: 22,
    fontVariantNumeric: "tabular-nums",
    letterSpacing: "-0.02em", lineHeight: 1,
  },
  movesSub: {
    fontFamily: "'Inter', system-ui, sans-serif",
    fontWeight: 600, fontSize: 11, color: "var(--text-sub)", marginLeft: 6,
    letterSpacing: "0.01em",
  },
  progressTrack: {
    height: 3, margin: "0 20px 12px",
    background: "var(--line)", borderRadius: 999, overflow: "hidden",
  },
  progressFill: {
    height: "100%", borderRadius: 999,
    transition: "width 400ms cubic-bezier(0.16, 1, 0.3, 1), background 300ms ease",
  },
  upgradeStrip: { display: "flex", gap: 4, padding: "0 20px 8px", flexWrap: "wrap" },
  board: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", padding: 20 },
  tubesRow: { display: "flex", flexWrap: "wrap", gap: 12, justifyContent: "center", alignItems: "flex-end", maxWidth: 400 },
  footer: {
    padding: "12px 20px calc(env(safe-area-inset-bottom, 0px) + 110px)",
    minHeight: 60,
    display: "flex", justifyContent: "center", alignItems: "center",
  },
  hint: {
    fontFamily: "'Inter', system-ui, sans-serif",
    fontSize: 12.5, fontWeight: 600, color: "var(--text-sub)",
    textAlign: "center", letterSpacing: "0.02em",
  },
  ovTop: { position: "fixed", inset: 0, background: "rgba(10,15,31,0.94)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20, backdropFilter: "blur(8px)", zIndex: 90 },
  overlay: { position: "fixed", inset: 0, background: "rgba(10,15,31,0.94)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20, backdropFilter: "blur(8px)" },
  ovCard: { background: T.card, border: `1px solid ${T.edge}`, borderRadius: 24, padding: 24, textAlign: "center", maxWidth: 320, width: "100%", boxShadow: "0 24px 60px rgba(0,0,0,0.5)" },
  ovIconCircle: { width: 64, height: 64, borderRadius: 20, background: `${T.danger}22`, border: `2px solid ${T.danger}55`, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 16px" },
  ovBigNum: { fontSize: 72, fontWeight: 900, color: T.ink, letterSpacing: "-0.05em", lineHeight: 1, marginTop: 8 },
  ovBigLabel: { fontSize: 11, fontWeight: 900, letterSpacing: "0.15em", color: T.muted, marginTop: 6, textTransform: "uppercase" },
  ovNewBest: { display: "inline-block", background: `${T.gold}22`, border: `1px solid ${T.gold}66`, color: T.gold, fontSize: 12, fontWeight: 900, padding: "6px 14px", borderRadius: 999, marginTop: 12 },
  ovStats: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 8, margin: "20px 0 20px" },
  ovStat: { background: `${T.bg}80`, border: `1px solid ${T.edge}`, borderRadius: 14, padding: "12px 6px", textAlign: "center" },
  ovStatNum: { fontSize: 22, fontWeight: 900, color: T.ink, letterSpacing: "-0.02em", fontVariantNumeric: "tabular-nums" },
  ovStatLabel: { fontSize: 9, fontWeight: 800, color: T.muted, letterSpacing: "0.08em", textTransform: "uppercase", marginTop: 4 },
  dailyBadge: { display: "inline-block", fontSize: 9, fontWeight: 900, letterSpacing: "0.1em", color: T.gold, background: `${T.gold}22`, border: `1px solid ${T.gold}66`, padding: "2px 6px", borderRadius: 6, marginRight: 6, verticalAlign: "middle" },
  comboBadge: {
    display: "flex", alignItems: "center", gap: 6,
    alignSelf: "center",
    background: "var(--gold-soft)",
    border: "1px solid var(--gold)",
    borderRadius: 999, padding: "5px 12px 5px 10px",
    marginBottom: 8,
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
  },
  comboFlame: { fontSize: 13 },
  comboText: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 12, fontWeight: 800, color: "var(--gold)",
    letterSpacing: "-0.01em", fontVariantNumeric: "tabular-nums",
  },
  /* ─── HOME SCREEN ─── */
  settingRow: { display: "flex", alignItems: "center", justifyContent: "space-between", width: "100%", background: `${T.bg}80`, border: `1px solid ${T.edge}`, borderRadius: 14, padding: "14px 16px", cursor: "pointer", fontFamily: "'Nunito', sans-serif", color: T.ink },
  settingLabel: { fontWeight: 800, fontSize: 14 },
  togglePill: { fontSize: 10, fontWeight: 900, letterSpacing: "0.1em", color: "#fff", padding: "4px 10px", borderRadius: 999 },
  tutOverlay: { position: "fixed", inset: 0, background: "rgba(10,15,31,0.95)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20, backdropFilter: "blur(10px)", zIndex: 100 },
  tutCard: { background: T.card, border: `1px solid ${T.edge}`, borderRadius: 28, padding: 28, maxWidth: 380, width: "100%", boxShadow: "0 32px 80px rgba(0,0,0,0.6)" },
  tutHeader: { textAlign: "center", marginBottom: 24 },
  tutIconCircle: { width: 64, height: 64, borderRadius: 20, background: `${T.accent}22`, border: `2px solid ${T.accent}55`, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 12px" },
  tutTitle: { fontWeight: 900, fontSize: 24, color: T.ink, letterSpacing: "-0.02em" },
  tutSub: { fontSize: 13, fontWeight: 700, color: T.muted, marginTop: 4 },
  tutSteps: { display: "flex", flexDirection: "column", gap: 14, marginBottom: 20 },
  tutStep: { display: "flex", alignItems: "flex-start", gap: 14 },
  tutNum: { width: 32, height: 32, borderRadius: 10, background: T.accent, color: "#fff", fontWeight: 900, fontSize: 15, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  tutStepBody: { flex: 1, minWidth: 0, paddingTop: 2 },
  tutStepTitle: { fontWeight: 900, fontSize: 15, color: T.ink },
  tutStepDesc: { fontSize: 13, fontWeight: 600, color: T.muted, marginTop: 2, lineHeight: 1.45 },
  tutWarning: { display: "flex", alignItems: "center", gap: 10, background: `${T.danger}15`, border: `1px solid ${T.danger}44`, borderRadius: 14, padding: "10px 14px", marginBottom: 20, fontSize: 12, fontWeight: 700, color: T.ink, lineHeight: 1.4 },
  ovTitle: { fontWeight: 900, fontSize: 28, letterSpacing: "-0.02em" },
  ovSub: { fontSize: 14, fontWeight: 600, color: T.muted, marginTop: 8, marginBottom: 24 },
  primary: { display: "block", width: "100%", background: T.accent, color: "#fff", border: "none", borderRadius: 999, padding: "14px 24px", fontFamily: "'Nunito', sans-serif", fontWeight: 900, fontSize: 15, cursor: "pointer", boxShadow: `0 8px 24px ${T.accent}55` },
  ghost: { display: "block", width: "100%", background: "transparent", color: T.muted, border: "none", padding: 12, fontFamily: "'Nunito', sans-serif", fontWeight: 800, fontSize: 13, cursor: "pointer", marginTop: 6 },
};
